fit  error TS2559: Type '4' has no properties in common with type 'MinMaxOptions'. fix err TypeScript-Node-Starter/src/controllers/api.ts[6, 9]: missing whitespace, 8 files fix bugs of issue 15